//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Andd
    {
        public int ID { get; set; }
        public string GymName { get; set; }
        public Nullable<System.DateTime> ApplicationEndDate { get; set; }
        public string Flag { get; set; }
        public string Description { get; set; }
    }
}
