//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbGymEntities : DbContext
    {
        public DbGymEntities()
            : base("name=DbGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MemberRegistration> MemberRegistrations { get; set; }
        public virtual DbSet<PackageDetail> PackageDetails { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PhysicalAssessment> PhysicalAssessments { get; set; }
        public virtual DbSet<TransactionPayment> TransactionPayments { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Andd> Andds { get; set; }
        public virtual DbSet<Confirm_MemberRegistration> Confirm_MemberRegistration { get; set; }
        public virtual DbSet<GymClose> GymCloses { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
    }
}
