//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalAssessment
    {
        public int ID { get; set; }
        public Nullable<int> MemberRegistration_PK_ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Biceps { get; set; }
        public string Triceps { get; set; }
        public string Shoulder { get; set; }
        public string Chest { get; set; }
        public string Wrist { get; set; }
        public string Thighs { get; set; }
        public string Fourarms { get; set; }
    
        public virtual MemberRegistration MemberRegistration { get; set; }
    }
}
