//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionPayment
    {
        public int ID { get; set; }
        public Nullable<int> MemberRegistration_PK_ID { get; set; }
        public Nullable<int> PaymentDetails_PK_ID { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string MobileNumber { get; set; }
        public string PaymentType { get; set; }
        public string Paid_Amount { get; set; }
        public string Due_Amount { get; set; }
        public string Total_Payment { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual MemberRegistration MemberRegistration { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
